Blog/urls.py
from django.urls import path 
from . import views

app_name = 'Blog'
urlpatterns = [
    # path('', views.post_list, name="post_list"),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share')
]

BlogApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls', namespace='blog')),
]

Blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class DraftManager(models.Manager):
    def get_queryset(self):
        return super(DraftManager, self).get_queryset().filter(status='draft')


class Post(models.Model):
    # Request status is defined using status_choices in which draft means just like email
    # and published is like email send
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=500)
    slug = models.CharField(max_length=500, unique_for_date='publish')
    author	=	models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()  # The default Mananger
    published = PublishedManager() # Our custom manager
    draft = DraftManager() 

    def get_absolute_url(self):
        return reverse("Blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

Blog/forms.py
from django import forms 
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length = 50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget = forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

Blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

# Create your views here.
# def post_list(request):
#     object_list = Post.published.all()
#     paginator = Paginator(object_list,3) #3 Post per page
#     page = request.GET.get('page')
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         #If page number is not an int return first page
#         posts = paginator.page(1)
#     except EmptyPage:
#         posts = paginator.page(paginator.num_pages)
#     context = {
#         'page': page,
#         'posts': posts,
#     }
#     return render(request,'Blog/post/list.html', context)

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 5
    template_name = 'Blog/post/list.html'

def post_detail(request,year,month,day,post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year = year,
    publish__month = month, publish__day = day)
    comments = post.comments.filter(active = True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    context = {
        'post':post,
        'comments':comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
    }
    return render(request, 'Blog/post/detail.html', context)

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status="published")
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST) #Form was submitted
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            #send _email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]}({cd["email"]}) recommends you reading "{post.title}"'
            message = f'Read "{post.title}" at {post_url}\n\n{cd["name"]}\'s comments:{cd["comments"]}'
            send_mail(subject,message,'preetshah964@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'post':post,
        'form':form,
        'sent': sent,
    }
    return render(request,'Blog/post/share.html', context)
    

Blog/templates/Blog/base.html
{% load static	%}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block	title %}{% endblock	%}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" 
	rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" 
	crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Digital Diary</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="./../../../../">Home</a>
        </li>
		</ul>
    </div>
  </div>
</nav>
	<div id="content" class="container">
	    {%	block content %}
	    {% endblock	%}
	</div>
	{% comment %} <div id="sidebar">
	    <h2>My blog</h2>
        <p>This	is my blog.</p>
	</div> {% endcomment %}
</body>
</html>

Blog/templates/Blog/post/detail.html
{% extends "Blog/base.html"%}

{% block title%}{{post.title}}{% endblock %}

{% block content %}
    <h1>
        {{post.title}}
    </h1>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
    {{post.body|linebreaks}}
    <p>
        <a href="{% url "blog:post_share" post.id%}" style="text-decoration: None;">
            Share the post
        </a>
    </p>
    {%	with comments.count	as total_comments %}
		<h4>
			Total number of comments: {{total_comments}}
		</h4>
    {% endwith %}
    {% for comment in comments %}
		<div class="comment">
				<p class="info">
					Comment	{{ forloop.counter }} by {{	comment.name	}}
						{{ comment.created }}
				</p>
				{{ comment.body|linebreaks }}
		</div>
    {% empty %}
		<p>There are no	comments yet.</p>
    {% endfor %}
    {% if new_comment %}
		<h2>Your comment has been added.</h2>
    {% else	%}
		<h2>Add	a new comment</h2>
		<form action="." method="post" style="">
			{{ comment_form.as_p}}
			{%	csrf_token	%}
			<p ><input	type="submit"	value="Add	comment" class="btn btn-dark"></p>
		</form>
    {%	endif	%}
{% endblock %}

Blog/templates/Blog/post/list.html
{% extends	"Blog/base.html" %}
{% block title %}My	Blog{% endblock	%}
{%	block content %}
	{% comment %} <h1>My Blog</h1> {% endcomment %}
	{%	for	post in	posts %}
	<h2>
	<a	href="{{ post.get_absolute_url}}" style="text-decoration: None;">
	{{post.title}}
	</a>
	</h2>
	<p	class="date">
	Published {{ post.publish }} by	{{ post.author }}
	</p>
	{{ post.body|truncatewords:30|linebreaks }}
	{% endfor %}
	{% include "pagination.html" with page=page_obj %}
{% endblock %}

Blog/templates/Blog/post/share.html
{% extends 'Blog/base.html'%}

{% block title%}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{post.title}} was successfully sen to {{form.cleaned_data.to}}"
        </p>
    {% else %}
        <h1>Share "{{post.title}}" by e-mail</h1>
        <form action = "." method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Send E-mail" class="btn btn-dark">
        </form>
    {% endif %}
{% endblock %}

Blog/templates/pagination.html
<div class="pagination">
    {% comment %} <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %} {% endcomment %}
        {% comment %} <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}
        </span> {% endcomment %}
        {% comment %} {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Next</a>
        {% endif %} {% endcomment %}
    {% comment %} </span> {% endcomment %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                {% if page.has_previous %}
                    <a class="page-link" href="?page={{page.previous_page_number}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    </a>
                {% endif %}
            </li>
            <li class="page-item"><a class="page-link" href="#">Page {{page.number}} of {{page.paginator.num_pages}}</a></li>
            <li class="page-item">
                {% if page.has_next %}
                    <a class="page-link" href="?page={{page.next_page_number}}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    </a>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>